<%@ Page Title="" Language="C#" MasterPageFile="~/View/Masterpage.Master" AutoEventWireup="true" CodeBehind="ManageRamenpage.aspx.cs" Inherits="RAAMEN.View.ManageRamenpage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView OnRowDeleting="userGv_RowDeleting" OnRowEditing="userGv_RowEditing" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" ID="RamenGV" AutoGenerateColumns="false" runat="server">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id"  />
            <asp:BoundField DataField="MeatId" HeaderText="Meat" />
            <asp:BoundField DataField="Broth" HeaderText="Broth" />
            <asp:BoundField DataField="Price" HeaderText="Price" />
        </Columns>
    </asp:GridView><br />
    <asp:Button ID="insertRamenBtn" runat="server" Text="Insert Ramen" OnClick="insertRamenBtn_Click" /><br />
</asp:Content>
